# 21.11.01. JAVA - 9일차

## 1101 수업 이슈

1. [Exception](##1.-Exception)
2. `JDBC` + SQL
3. JAVA필기시험 --- 4시

## 1. Exception

public class Exception
extends Throwable


The class `Exception` and its subclasses are a form of `Throwable` that indicates conditions that a reasonable application might want to catch.

The class `Exception` and any subclasses that are not also subclasses of [`RuntimeException`](https://docs.oracle.com/javase/8/docs/api/java/lang/RuntimeException.html) are *checked exceptions*. Checked exceptions need to be declared in a method or constructor's `throws` clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.

![](./image/1101-01.png)

```java
package exception.runtime.test;

public class RuntimeExceptionTest1 {

	public static void main(String[] args) {
		String[ ] str = {
				"Hello JAVA",
				"No, I Mean it",
				"Nice to meet you"
		};
		int i =0;
		while(i<=3) {
			System.out.println(str[i]);
			i++;
		}
		System.out.println("while loop the end...");
	}

}
```

* 출력이 되었는데,,,

```java
Hello JAVA
No, I Mean it
Nice to meet you
    //str 데이터는 출력이 되었음. 하지만
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at exception.runtime.test.RuntimeExceptionTest1.main(RuntimeExceptionTest1.java:13)
    //프로그램이 정상 종료가 되지 않음.

```

#### `str`데이터 출력은 되었지만, 프로그램이 정상 종료가 되지는 않음.

컴파일러가 인식 못함.

RuntimeException

실행에서 문제가 생김.



### 문제의 원인 : i=3일때, 문제가 생김.

예외는 Method Block안에서 줄단위로 발생한다!

![](./image/1101-02.png)





